//import "./governance/index"
import "./mainnet/index"
import "./mainnetLive/index"
import "./IPTsale/index"
import "./isolated/index"
import "./cap/index"
import "./rewards/index"
import "./upgrades/index"