/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as external from "./External";
export type { external };
import type * as logic from "./Logic";
export type { logic };
export type { IOracleMaster } from "./IOracleMaster";
export type { IOracleRelay } from "./IOracleRelay";
export type { OracleMaster } from "./OracleMaster";
