/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOracleRelay,
  IOracleRelayInterface,
} from "../../oracle/IOracleRelay";

const _abi = [
  {
    inputs: [],
    name: "currentValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IOracleRelay__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleRelayInterface {
    return new utils.Interface(_abi) as IOracleRelayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleRelay {
    return new Contract(address, _abi, signerOrProvider) as IOracleRelay;
  }
}
