/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IAggregator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAggregator__factory>;
    getContractFactory(
      name: "ERC20Detailed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Detailed__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IUniswapV3PoolDerivedState",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV3PoolDerivedState__factory>;
    getContractFactory(
      name: "CurveMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CurveMaster__factory>;
    getContractFactory(
      name: "ICurveMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICurveMaster__factory>;
    getContractFactory(
      name: "ICurveSlave",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICurveSlave__factory>;
    getContractFactory(
      name: "ThreeLines0_100",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThreeLines0_100__factory>;
    getContractFactory(
      name: "IVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVault__factory>;
    getContractFactory(
      name: "IVaultMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultMaster__factory>;
    getContractFactory(
      name: "CompLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CompLike__factory>;
    getContractFactory(
      name: "Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Vault__factory>;
    getContractFactory(
      name: "VaultMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultMaster__factory>;
    getContractFactory(
      name: "Migrations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Migrations__factory>;
    getContractFactory(
      name: "ChainlinkOracleRelay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ChainlinkOracleRelay__factory>;
    getContractFactory(
      name: "UniswapV3OracleRelay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapV3OracleRelay__factory>;
    getContractFactory(
      name: "IOracleMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOracleMaster__factory>;
    getContractFactory(
      name: "IOracleRelay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOracleRelay__factory>;
    getContractFactory(
      name: "AnchoredViewRelay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AnchoredViewRelay__factory>;
    getContractFactory(
      name: "OracleMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OracleMaster__factory>;
    getContractFactory(
      name: "BeaconProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BeaconProxy__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "UpgradeableBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeableBeacon__factory>;
    getContractFactory(
      name: "ERC1967Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Proxy__factory>;
    getContractFactory(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Upgrade__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "ProxyAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProxyAdmin__factory>;
    getContractFactory(
      name: "TransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransparentUpgradeableProxy__factory>;
    getContractFactory(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeable__factory>;
    getContractFactory(
      name: "IUSDI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUSDI__factory>;
    getContractFactory(
      name: "UFragments",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UFragments__factory>;
    getContractFactory(
      name: "USDI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.USDI__factory>;

    getContractAt(
      name: "IAggregator",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAggregator>;
    getContractAt(
      name: "ERC20Detailed",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Detailed>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IUniswapV3PoolDerivedState",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV3PoolDerivedState>;
    getContractAt(
      name: "CurveMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CurveMaster>;
    getContractAt(
      name: "ICurveMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICurveMaster>;
    getContractAt(
      name: "ICurveSlave",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICurveSlave>;
    getContractAt(
      name: "ThreeLines0_100",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThreeLines0_100>;
    getContractAt(
      name: "IVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVault>;
    getContractAt(
      name: "IVaultMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultMaster>;
    getContractAt(
      name: "CompLike",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CompLike>;
    getContractAt(
      name: "Vault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Vault>;
    getContractAt(
      name: "VaultMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultMaster>;
    getContractAt(
      name: "Migrations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Migrations>;
    getContractAt(
      name: "ChainlinkOracleRelay",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ChainlinkOracleRelay>;
    getContractAt(
      name: "UniswapV3OracleRelay",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapV3OracleRelay>;
    getContractAt(
      name: "IOracleMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOracleMaster>;
    getContractAt(
      name: "IOracleRelay",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOracleRelay>;
    getContractAt(
      name: "AnchoredViewRelay",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AnchoredViewRelay>;
    getContractAt(
      name: "OracleMaster",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OracleMaster>;
    getContractAt(
      name: "BeaconProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BeaconProxy>;
    getContractAt(
      name: "IBeacon",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "UpgradeableBeacon",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeableBeacon>;
    getContractAt(
      name: "ERC1967Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Proxy>;
    getContractAt(
      name: "ERC1967Upgrade",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Upgrade>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "ProxyAdmin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ProxyAdmin>;
    getContractAt(
      name: "TransparentUpgradeableProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TransparentUpgradeableProxy>;
    getContractAt(
      name: "UUPSUpgradeable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeable>;
    getContractAt(
      name: "IUSDI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUSDI>;
    getContractAt(
      name: "UFragments",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UFragments>;
    getContractAt(
      name: "USDI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.USDI>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
